id: IDEDD05CF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T01:00:22+00:00'
last_modified: '2022-06-08T13:28:55.134356+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20495
  title: ནག་པོ་སྐལ་བཟང་གི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    0FE0:
      image_group_id: I8LS20497
      title: Volume 1 of mchog sprul nag po skal bzang gi gsung rtsom phyogs bsgrigs/
      total_pages: 314
      order: 1
      base_file: 0FE0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
