id: P007035
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20495
  title: ནག་པོ་སྐལ་བཟང་གི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    ea25dc26923d4a6b8b97667f5cac7162:
      image_group_id: I8LS20497
      title: ''
      volume_number: 1
      total_pages: 314
ebook_metadata:
  title: ནག་པོ་སྐལ་བཟང་གི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P007035
  cover: cover.jpg
  layers:
  - pagination
